"use strict";
const { Router } = require("express");
const ctrl = require("./workOrder.controller.js");
const router = Router();
router.get("/", ctrl.list);
router.get("/:id", ctrl.getById);
router.post("/", ctrl.create);
router.put("/:id", ctrl.update);
router.patch("/:id/status", ctrl.updateStatus);
router.delete("/:id", ctrl.remove);
module.exports = router;
